project:
  type: website

website:
  title: "DASTAT"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Sobre"
        href: about.qmd
      - text: "Projetos"
        href: projects.qmd
      - text: "Serviços"
        href: services.qmd
      - text: "Contato"
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

# Configura a pasta de saída para 'docs'
output-dir: docs
