project:
  type: website

website:
  title: "Dastat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

# Configura a pasta de saída para 'docs'
output-dir: docs
